# Create a fixed workflow that addresses both issues
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: fixed-ci-
spec:
  entrypoint: main
  templates:
  - name: main
    steps:
    - - name: clone-and-test
        template: clone-test-build
    - - name: build-and-push
        template: kaniko-build  # Using Kaniko instead of Docker for Kubernetes-native builds

  - name: clone-test-build
    container:
      image: node:18-alpine
      workingDir: /workspace
      command: [sh, -c]
      args:
        - |
          echo "🚀 STARTING CI PIPELINE..."
          
          # Clone to current directory (not subdirectory)
          echo "📦 Cloning repository..."
          apk add --no-cache git
          git clone https://github.com/vasplustechnologies/patient-appointment-api.git /workspace
          
          echo "📁 Checking files..."
          ls -la
          
          echo "🧪 Installing dependencies..."
          npm install
          
          echo "🔬 Running tests..."
          npm test
          
          echo "✅ Tests completed successfully!"

  - name: kaniko-build
    container:
      image: gcr.io/kaniko-project/executor:latest
      workingDir: /workspace
      command: [sh, -c]
      args:
        - |
          echo "🐳 Cloning repository for build..."
          apk add --no-cache git
          git clone https://github.com/vasplustechnologies/patient-appointment-api.git /workspace
          
          echo "📁 Files in workspace:"
          ls -la
          
          echo "🔨 Building and pushing with Kaniko..."
          /kaniko/executor \
            --context=dir:///workspace \
            --destination=mofwili/patient-appointment-api:latest \
            --cache=true \
            --verbosity=info
          
          echo "🎉 SUCCESS! Image built and pushed to DockerHub!"
          echo "📦 Image: mofwili/patient-appointment-api:latest"
      env:
      - name: DOCKER_CONFIG
        value: /kaniko/.docker
      volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
    volumes:
    - name: kaniko-secret
      secret:
        secretName: dockerhub-credentials
        items:
        - key: .dockerconfigjson
          path: config.json
